using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public enum EndingType { Royal, Rival, Slum, BankruptEarly, BankruptLate }

/// <summary>
/// Persistent singleton holding all shared state across scenes.
/// Add this GO to every scene; duplicates are destroyed automatically.
/// </summary>
[DisallowMultipleComponent]
public class GameManager : MonoBehaviour
{
    // ── Singleton ──────────────────────────────────────────────────

    public static GameManager Instance { get; private set; }

    // ── Scene name constants ───────────────────────────────────────

    public const string SCENE_TITLE      = "TitleScene";
    public const string SCENE_CUSTOMER   = "CustomerGeneratorTest";
    public const string SCENE_MARKET     = "MaterialGeneratorTest";
    public const string SCENE_CRAFTING   = "CraftingScene";
    public const string SCENE_MINIGAME   = "MinigameTest";
    public const string SCENE_EVALUATION = "EvaluationScene";
    public const string SCENE_MORNING    = "MorningScene";
    public const string SCENE_ENDING     = "EndingScene";

    // ── Progression constants (tweak these to tune difficulty) ────

    public const int TOTAL_DAYS        = 7;
    public const int STARTING_GOLD     = 500;
    public const int ROYAL_REP_MIN     = 90;   // ≥ this → Royal ending
    public const int RIVAL_REP_MIN     = 30;   // in [RIVAL_REP_MIN, ROYAL_REP_MIN) → Rival

    // Rent is billed at the END of day 3 (before day 4) and day 6 (before day 7).
    public static readonly int[] RENT_DUE_DAYS = { 3, 6 };
    public static readonly int[] RENT_AMOUNTS  = { 250, 400 };

    // ── Shared round state ───────────────────────────────────────

    [HideInInspector] public CustomerOrder      currentCustomer;
    [HideInInspector] public PlayerMemo         currentMemo;

    // Pre-generated by MorningScene's API call so the CustomerGenerator scene
    // can skip its own API roundtrip when the player clicks "Meet the first
    // customer". `pendingCustomerInProgress` is true while the request is mid-
    // flight; CustomerGenerator polls this to decide whether to wait or fire
    // its own request.
    [HideInInspector] public CustomerOrder      pendingCustomer;
    [HideInInspector] public bool               pendingCustomerInProgress;

    // Pre-generated material list (text + in-flight images) so the
    // MaterialGenerator scene can skip its own OpenAI roundtrip and many
    // of its ComfyUI roundtrips when the player arrives there. Populated
    // by MaterialService.PreGenAsync, consumed by MaterialGenerator.Start.
    [HideInInspector] public List<MaterialData> pendingMaterials;
    [HideInInspector] public bool               pendingMaterialsInProgress;
    [HideInInspector] public List<MaterialData> availableMaterials = new();
    [HideInInspector] public List<MaterialData> inventory          = new();
    [HideInInspector] public int                playerGold         = STARTING_GOLD;
    [HideInInspector] public int                playerReputation   = 0;
    [HideInInspector] public WandResult         currentWandResult;
    [HideInInspector] public char               craftingQualityGrade = 'A';

    // Material picks committed in CraftingScene; consumed in MinigameScene
    // by the wand-generation pipeline that runs in parallel with the minigame.
    [HideInInspector] public MaterialData       chosenCore1;
    [HideInInspector] public MaterialData       chosenCore2;
    [HideInInspector] public MaterialData       chosenWood;

    // Per-round score breakdown surfaced on the Evaluation result screen.
    [HideInInspector] public int                lastMinigameRoundsWon  = 0;
    [HideInInspector] public int                lastMatchScore         = 0;

    // ── Progression state (persists across scenes, resets on new run) ─

    [HideInInspector] public int  currentDay         = 1;
    [HideInInspector] public int  peakReputation     = 0;
    [HideInInspector] public int  wandsCrafted       = 0;
    [HideInInspector] public int  lettersReceived    = 0;
    [HideInInspector] public bool bankruptedOnDay3   = false;

    // ── Unity lifecycle ────────────────────────────────────────────

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }
        Instance = this;
        DontDestroyOnLoad(gameObject);
    }

    // ── Gold ──────────────────────────────────────────────────────

    public void AddGold(int amount)  => playerGold += amount;
    public void SpendGold(int amount) => playerGold -= amount;
    public bool CanAfford(int price)  => playerGold >= price;

    // ── Inventory ─────────────────────────────────────────────────

    public void AddToInventory(MaterialData material)    => inventory.Add(material);
    public void RemoveFromInventory(MaterialData material) => inventory.Remove(material);

    // ── Navigation ────────────────────────────────────────────────

    public void LoadScene(string sceneName)
    {
        // Scene files are prefixed with their build index (e.g. "1.MorningScene.unity")
        // so the Project window orders them, but the SCENE_* constants stay un-prefixed.
        // Resolve by iterating build settings and matching either the exact file name or
        // a "<index>.<sceneName>" pattern.
        int sceneCount = SceneManager.sceneCountInBuildSettings;
        for (int i = 0; i < sceneCount; i++)
        {
            string path     = SceneUtility.GetScenePathByBuildIndex(i);
            string fileName = System.IO.Path.GetFileNameWithoutExtension(path);
            if (fileName == sceneName || fileName.EndsWith("." + sceneName))
            {
                SceneManager.LoadScene(i);
                return;
            }
        }
        Debug.LogError($"[GameManager] Scene '{sceneName}' not found in build settings. " +
                       $"Add it via File → Build Profiles.");
    }

    // ── Round reset (legacy — kept for MinigameTest + any standalone entry) ─

    public void StartNextRound()
    {
        currentCustomer    = null;
        currentMemo        = null;
        pendingCustomer    = null;
        pendingCustomerInProgress = false;
        pendingMaterials   = null;
        pendingMaterialsInProgress = false;
        availableMaterials = new List<MaterialData>();
        currentWandResult      = null;
        craftingQualityGrade   = 'A';
        chosenCore1 = chosenCore2 = chosenWood = null;
        lastMinigameRoundsWon  = 0;
        lastMatchScore         = 0;
        LoadScene(SCENE_CUSTOMER);
    }

    // ── Day progression (new flow used by EvaluationManager) ──────

    public void AdvanceToNextDay()
    {
        currentDay++;
        currentCustomer      = null;
        currentMemo          = null;
        pendingCustomer      = null;
        pendingCustomerInProgress = false;
        availableMaterials   = new List<MaterialData>();
        currentWandResult    = null;
        craftingQualityGrade = 'A';
        chosenCore1 = chosenCore2 = chosenWood = null;
        lastMinigameRoundsWon  = 0;
        lastMatchScore         = 0;
        LoadScene(SCENE_MORNING);
    }

    public bool IsRentDueToday() => System.Array.IndexOf(RENT_DUE_DAYS, currentDay) >= 0;

    public int GetRentDueToday()
    {
        int idx = System.Array.IndexOf(RENT_DUE_DAYS, currentDay);
        return idx >= 0 ? RENT_AMOUNTS[idx] : 0;
    }

    public EndingType DetermineEnding()
    {
        if (playerReputation >= ROYAL_REP_MIN) return EndingType.Royal;
        if (playerReputation >= RIVAL_REP_MIN) return EndingType.Rival;
        return EndingType.Slum;
    }

    public void ResetForNewPlaythrough()
    {
        currentCustomer      = null;
        currentMemo          = null;
        pendingCustomer      = null;
        pendingCustomerInProgress = false;
        pendingMaterials     = null;
        pendingMaterialsInProgress = false;
        availableMaterials   = new List<MaterialData>();
        inventory            = new List<MaterialData>();
        playerGold           = STARTING_GOLD;
        playerReputation     = 0;
        currentWandResult    = null;
        craftingQualityGrade = 'A';
        chosenCore1 = chosenCore2 = chosenWood = null;
        lastMinigameRoundsWon  = 0;
        lastMatchScore         = 0;
        currentDay           = 1;
        peakReputation       = 0;
        wandsCrafted         = 0;
        lettersReceived      = 0;
        bankruptedOnDay3     = false;
    }

    // ── Editor-only dev shortcuts (speed up testing without 7 playthroughs) ─

#if UNITY_EDITOR
    [ContextMenu("Dev/Jump to Day 3 (pre-rent)")]
    private void DevJumpToDay3() { currentDay = 3; }

    [ContextMenu("Dev/Jump to Day 6 (pre-rent)")]
    private void DevJumpToDay6() { currentDay = 6; }

    [ContextMenu("Dev/Jump to Day 7 (pre-ending)")]
    private void DevJumpToDay7() { currentDay = 7; }

    [ContextMenu("Dev/Force Royal-tier reputation (120)")]
    private void DevForceRoyalRep() { playerReputation = 120; peakReputation = 120; }

    [ContextMenu("Dev/Force Rival-tier reputation (55)")]
    private void DevForceRivalRep() { playerReputation = 55; peakReputation = 55; }

    [ContextMenu("Dev/Force Slum-tier reputation (-20)")]
    private void DevForceSlumRep() { playerReputation = -20; }

    [ContextMenu("Dev/Empty wallet (test bankruptcy)")]
    private void DevEmptyWallet() { playerGold = 50; }
#endif
}
