"""Score the customer-dossier outputs from `run_llm_study.py` on a five-axis rubric
using an LLM-as-judge (Claude Opus, family-distinct from every candidate).

Each output is judged 3× and the median is reported, controlling for judge
variance. Emits two files:

    .claude/Final Report/llm_study/results.csv      — one row per (model, seed, axis)
    .claude/Final Report/llm_study/summary.csv      — one row per model, mean across runs

Rubric axes:

    1. coherence        constraint logically explains request                (0/1/2)
    2. misdirection     trueGoal differs from request in a meaningful way   (0/1/2)
    3. tone             reads as cosy fantasy authored prose, not templated (0/1/2)
    4. playability      a player could distil a 4-slot memo in 30–60 s      (0/1/2)
    5. wellformed       JSON parsed cleanly without strip-fences            (0/1)

Plus a non-rubric pass-through column:

    parse_ok            from the runner record                              (bool)

Usage:
    py tools/score_llm_study.py            # judges everything in llm_study/
    py tools/score_llm_study.py --judge claude-sonnet-4-5    # cheaper judge
    py tools/score_llm_study.py --limit 5  # quick sanity run

Cost: ~$0.05 per output × 3 judges ≈ $0.15 per model column.
Full study (8 models × 30 outputs × 3 judge runs × ~$0.005) ≈ $3.60.
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import statistics
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
STUDY_DIR    = PROJECT_ROOT / ".claude" / "Final Report" / "llm_study"
ENV_FILE     = STUDY_DIR / ".env"


JUDGE_SYSTEM = """You are a strict, fair judge evaluating customer dossiers
generated by language models for a fantasy wand-crafting game.

You receive ONE candidate dossier as JSON. Score it on five axes. Be calibrated:
the in-house GPT-4o reference adheres to the rubric ~93% of the time, so a clean
GPT-4o-style dossier should score 2/2 on most axes, and only borderline or
template-feeling outputs should drop to 1 or 0.

Score each axis using this scale and these definitions:

  coherence    [0|1|2]
    Does the constraint logically EXPLAIN the request? (Not just be plausible.)
    2 = explicit causal chain ("She X, therefore she needs Y")
    1 = compatible but not tightly causal
    0 = unrelated or contradictory

  misdirection [0|1|2]
    Are the request and trueGoal meaningfully different (request is the
    surface ask; trueGoal is the deeper need)?
    2 = clearly distinct, mechanically informative gap
    1 = trueGoal is a slight elaboration of request
    0 = trueGoal is a paraphrase of request

  tone         [0|1|2]
    Does it read as authored cosy-fantasy prose, not templated?
    2 = specific imagery, character-voice in `request`
    1 = competent but generic
    0 = robotic, list-like, or includes meta-text

  playability  [0|1|2]
    Could a player extract a 4-slot memo (Element/Personality/Purpose/
    Reinforcement) in 30–60 s of reading?
    2 = each slot has an obvious anchor phrase
    1 = one slot is ambiguous
    0 = multiple slots are not derivable from the dossier

  wellformed   [0|1]
    1 = JSON parsed cleanly with all 7 required fields populated
    0 = malformed, missing fields, or wrapped in markdown fences

Return ONLY a single JSON object, no prose, no markdown:
{
  "coherence": int,
  "misdirection": int,
  "tone": int,
  "playability": int,
  "wellformed": int,
  "rationale": "one short sentence summarising your reasoning"
}"""


def load_env():
    if not ENV_FILE.exists():
        return
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        if v:
            os.environ.setdefault(k.strip(), v.strip())


def judge_call(judge_model: str, dossier_text: str) -> dict:
    """Call the judge once. Returns the parsed score dict, or a sentinel
    {'error': '...'} on failure."""
    import anthropic
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    user = (
        "Candidate dossier (verbatim model output):\n\n"
        + dossier_text
        + "\n\nScore now."
    )
    try:
        resp = client.messages.create(
            model=judge_model,
            max_tokens=512,
            system=JUDGE_SYSTEM,
            messages=[{"role": "user", "content": user}],
        )
        text = "".join(b.text for b in resp.content if hasattr(b, "text"))
        m = re.search(r"\{.*\}", text, re.S)
        if not m:
            return {"error": "no JSON in judge output"}
        return json.loads(m.group(0))
    except Exception as exc:
        return {"error": f"{type(exc).__name__}: {exc}"}


def median_score(scores: list[dict], axis: str) -> float | None:
    vals = [s[axis] for s in scores if axis in s and isinstance(s[axis], (int, float))]
    if not vals:
        return None
    return statistics.median(vals)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--judge", default="claude-opus-4-5",
                        help="judge model (default claude-opus-4-5; "
                             "use claude-sonnet-4-5 for cheaper judging)")
    parser.add_argument("--n-judges", type=int, default=3,
                        help="how many judge calls per output (median across runs)")
    parser.add_argument("--limit", type=int, default=None,
                        help="cap to N outputs per model (debugging)")
    args = parser.parse_args()

    load_env()
    if "ANTHROPIC_API_KEY" not in os.environ:
        sys.exit("ANTHROPIC_API_KEY not set; cannot run judge.")

    # Discover outputs
    all_outputs = []  # list of (model_folder, run_index, file_path, record)
    for model_dir in sorted(STUDY_DIR.iterdir()):
        if not model_dir.is_dir() or model_dir.name.startswith("."):
            continue
        files = sorted(model_dir.glob("*.json"))
        if args.limit:
            files = files[: args.limit]
        for i, fp in enumerate(files):
            try:
                rec = json.loads(fp.read_text(encoding="utf-8"))
            except Exception:
                continue
            all_outputs.append((model_dir.name, i, fp, rec))

    if not all_outputs:
        sys.exit(f"no outputs found under {STUDY_DIR}; run run_llm_study.py first.")

    print(f"judging {len(all_outputs)} outputs × {args.n_judges} runs = "
          f"{len(all_outputs) * args.n_judges} judge calls")

    rows_long = []  # detailed per-(model, seed, axis) rows
    judge_history = {}  # (model, seed_idx) -> list of judge dicts

    for idx, (model_name, run_idx, fp, rec) in enumerate(all_outputs, start=1):
        candidate_text = rec.get("raw_response") or "<empty>"
        per_run_scores = []
        for j in range(args.n_judges):
            t0 = time.perf_counter()
            score = judge_call(args.judge, candidate_text)
            dt = (time.perf_counter() - t0) * 1000
            per_run_scores.append(score)
            err = score.get("error")
            print(f"[{idx:3d}/{len(all_outputs)}] {model_name:18s} run {run_idx:02d} j{j+1} "
                  f"{dt:5.0f} ms  {'ERR' if err else 'ok'}")
        judge_history[(model_name, run_idx)] = per_run_scores

        for axis in ("coherence", "misdirection", "tone", "playability", "wellformed"):
            med = median_score(per_run_scores, axis)
            rows_long.append({
                "model":  model_name,
                "run":    run_idx,
                "seed":   rec.get("seed", ""),
                "axis":   axis,
                "median": med,
                "parse_ok": rec.get("parse_ok"),
                "latency_ms": rec.get("latency_ms"),
                "cost_usd":   rec.get("cost_usd"),
            })

    # Long-form CSV
    long_path = STUDY_DIR / "results.csv"
    with long_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows_long[0].keys()))
        w.writeheader()
        w.writerows(rows_long)
    print(f"wrote {long_path}")

    # Summary CSV — one row per model, mean across the 30 runs per axis,
    # plus mean latency / cost / parse-ok rate.
    summary_path = STUDY_DIR / "summary.csv"
    by_model: dict[str, dict] = {}
    for r in rows_long:
        m = r["model"]
        by_model.setdefault(m, {
            "model": m,
            "n": 0,
            "coherence": [], "misdirection": [], "tone": [],
            "playability": [], "wellformed": [],
            "latency_ms": [], "cost_usd": [], "parse_ok": [],
        })
    # increment n once per (model, run)
    seen = set()
    for r in rows_long:
        if (r["model"], r["run"]) not in seen:
            by_model[r["model"]]["n"] += 1
            seen.add((r["model"], r["run"]))
            if r["latency_ms"] is not None:
                by_model[r["model"]]["latency_ms"].append(r["latency_ms"])
            if r["cost_usd"] is not None:
                by_model[r["model"]]["cost_usd"].append(r["cost_usd"])
            by_model[r["model"]]["parse_ok"].append(1 if r["parse_ok"] else 0)
        if r["median"] is not None:
            by_model[r["model"]][r["axis"]].append(r["median"])

    with summary_path.open("w", encoding="utf-8", newline="") as f:
        cols = ["model", "n", "coherence_mean", "misdirection_mean", "tone_mean",
                "playability_mean", "wellformed_mean", "parse_ok_pct",
                "latency_ms_mean", "latency_ms_p95",
                "cost_per_call_mean", "cost_per_session_estimate"]
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for m, d in sorted(by_model.items()):
            def avg(xs): return round(statistics.mean(xs), 3) if xs else None
            def pct(xs): return round(100 * statistics.mean(xs), 1) if xs else None
            def p95(xs):
                if not xs: return None
                xs2 = sorted(xs); k = max(0, int(len(xs2) * 0.95) - 1)
                return xs2[k]
            w.writerow({
                "model": m,
                "n": d["n"],
                "coherence_mean": avg(d["coherence"]),
                "misdirection_mean": avg(d["misdirection"]),
                "tone_mean": avg(d["tone"]),
                "playability_mean": avg(d["playability"]),
                "wellformed_mean": avg(d["wellformed"]),
                "parse_ok_pct": pct(d["parse_ok"]),
                "latency_ms_mean": avg(d["latency_ms"]),
                "latency_ms_p95":  p95(d["latency_ms"]),
                "cost_per_call_mean": avg(d["cost_usd"]),
                # 4 customer calls/day × 7 days = 28 dossier-equivalent calls per session
                "cost_per_session_estimate": (
                    round(28 * statistics.mean(d["cost_usd"]), 4) if d["cost_usd"] else None
                ),
            })
    print(f"wrote {summary_path}")
    print("\ndone.")


if __name__ == "__main__":
    sys.exit(main() or 0)
